mod commands;
mod config;
mod db;
mod error;

use db::{init_database, DbState};
use std::sync::OnceLock;

static DB_STATE: OnceLock<DbState> = OnceLock::new();

pub fn run() {
    env_logger::init();

    let app_config = config::AppConfig::default();

    let db_path = app_config.db_path.to_string_lossy().to_string();

    if let Some(parent) = app_config.db_path.parent() {
        std::fs::create_dir_all(parent).expect("Failed to create database directory");
    }

    let conn = init_database(&db_path).expect("Failed to initialize database");

    let db_state = DbState::new(conn);
    DB_STATE.set(db_state).expect("Failed to set database state");

    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .invoke_handler(tauri::generate_handler![
            commands::app::get_app_version,
            commands::app::health_check,
            commands::app::greet,
            commands::app::run_seeds,
            commands::auth::login,
            commands::auth::logout,
            commands::auth::get_current_user,
            commands::auth::check_session,
            commands::auth::get_user_permissions_list,
            commands::auth::login_by_role,
            commands::settings::get_settings,
            commands::settings::get_setting,
            commands::settings::update_setting,
            commands::settings::get_settings_by_group,
            commands::inventory::get_categories,
            commands::inventory::create_category,
            commands::inventory::update_category,
            commands::inventory::archive_category,
            commands::inventory::restore_category,
            commands::inventory::get_brands,
            commands::inventory::create_brand,
            commands::inventory::update_brand,
            commands::inventory::archive_brand,
            commands::inventory::get_manufacturers,
            commands::inventory::create_manufacturer,
            commands::inventory::update_manufacturer,
            commands::inventory::get_suppliers,
            commands::inventory::create_supplier,
            commands::inventory::update_supplier,
            commands::inventory::archive_supplier,
            commands::inventory::get_warehouses,
            commands::inventory::create_warehouse,
            commands::inventory::update_warehouse,
            commands::inventory::get_storage_locations,
            commands::inventory::create_storage_location,
            commands::inventory::update_storage_location,
            commands::inventory::archive_storage_location,
            commands::inventory::get_products,
            commands::inventory::get_product,
            commands::inventory::create_product,
            commands::inventory::update_product,
            commands::inventory::archive_product,
            commands::inventory::restore_product,
            commands::inventory::get_dashboard_stats,
            commands::inventory::get_inventory_movements,
            commands::inventory::create_inventory_movement,
            commands::inventory::get_product_images,
            commands::inventory::create_product_image,
            commands::inventory::delete_product_image,
            commands::customers::get_customers,
            commands::customers::get_customer,
            commands::customers::create_customer,
            commands::customers::update_customer,
            commands::customers::archive_customer,
            commands::customers::get_customer_detail,
            commands::customers::get_customer_sales,
            commands::customers::get_credit_accounts,
            commands::customers::get_credit_account,
            commands::customers::create_credit_account,
            commands::customers::update_credit_account,
            commands::customers::get_credit_transactions,
            commands::customers::add_credit_transaction,
            commands::customers::get_communications,
            commands::customers::create_communication,
            commands::customers::get_customer_notes,
            commands::customers::create_customer_note,
            commands::customers::get_customer_timeline,
            commands::vehicles::get_vehicle_brands,
            commands::vehicles::create_vehicle_brand,
            commands::vehicles::update_vehicle_brand,
            commands::vehicles::get_vehicle_models,
            commands::vehicles::create_vehicle_model,
            commands::vehicles::get_vehicle_generations,
            commands::vehicles::create_vehicle_generation,
            commands::vehicles::get_vehicle_engines,
            commands::vehicles::create_vehicle_engine,
            commands::vehicles::get_vehicle_transmissions,
            commands::vehicles::create_vehicle_transmission,
            commands::vehicles::get_vehicle_fuels,
            commands::vehicles::create_vehicle_fuel,
            commands::vehicles::get_customer_vehicles,
            commands::vehicles::get_customer_vehicle,
            commands::vehicles::create_customer_vehicle,
            commands::vehicles::update_customer_vehicle,
            commands::vehicles::delete_customer_vehicle,
            commands::compatibility::get_product_compatibility,
            commands::compatibility::create_compatibility,
            commands::compatibility::delete_compatibility,
            commands::compatibility::search_compatible_products,
            commands::compatibility::get_recommendations_for_vehicle,
            commands::reminders::get_service_reminders,
            commands::reminders::get_service_reminder,
            commands::reminders::create_service_reminder,
            commands::reminders::update_service_reminder_status,
            commands::reminders::get_overdue_reminders,
            commands::warranty::get_warranties,
            commands::warranty::get_warranty,
            commands::warranty::create_warranty,
            commands::warranty::update_warranty_status,
            commands::warranty::get_expiring_warranties,
            commands::crm::get_crm_dashboard,
            commands::crm::get_customers_by_month,
            commands::sales::get_sales,
            commands::sales::get_sale,
            commands::sales::get_sale_items,
            commands::sales::create_sale,
            commands::sales::refund_sale,
            commands::sales::get_daily_closeout,
            commands::sales::search_products_for_pos,
            commands::sales::process_checkout,
            commands::sales::get_sale_payments,
            commands::sales::get_sales_summary,
            commands::sales::get_sales_chart_data,
            commands::sales::search_sales,
            commands::sales::get_quotes,
            commands::sales::get_quote,
            commands::sales::get_quote_items,
            commands::sales::create_quote,
            commands::sales::update_quote,
            commands::sales::delete_quote,
            commands::sales::update_quote_status,
            commands::sales::convert_quote_to_sale,
            commands::sales::get_cash_register_status,
            commands::sales::open_cash_register,
            commands::sales::close_cash_register,
            commands::sales::get_cash_register_sessions,
            commands::sales::close_daily_shift,
            commands::sales::get_daily_closings,
            commands::sales::get_receipts_for_sale,
            commands::sales::get_receipt,
            commands::sales::mark_receipt_printed,
            commands::purchases::get_purchase_orders,
            commands::purchases::get_purchase_order,
            commands::purchases::get_purchase_order_items,
            commands::purchases::create_purchase_order,
            commands::purchases::update_purchase_order,
            commands::purchases::update_purchase_order_status,
            commands::purchases::delete_purchase_order,
            commands::purchases::get_purchase_requests,
            commands::purchases::get_purchase_request,
            commands::purchases::get_purchase_request_items,
            commands::purchases::create_purchase_request,
            commands::purchases::update_purchase_request_status,
            commands::purchases::get_purchase_receipts,
            commands::purchases::get_purchase_receipt,
            commands::purchases::get_purchase_receipt_items,
            commands::purchases::receive_purchase_order,
            commands::purchases::get_purchase_returns,
            commands::purchases::get_purchase_return,
            commands::purchases::get_purchase_return_items,
            commands::purchases::create_purchase_return,
            commands::purchases::get_supplier_products,
            commands::purchases::create_supplier_product,
            commands::purchases::update_supplier_product,
            commands::purchases::delete_supplier_product,
            commands::purchases::get_cost_history,
            commands::purchases::get_purchase_dashboard,
            commands::purchases::get_reorder_suggestions,
            commands::purchases::get_supplier_performance,
            // ── Reports ──
            commands::reports::get_executive_dashboard,
            commands::reports::get_dashboard_widgets,
            commands::reports::get_chart_data,
            // Sales Reports
            commands::reports::get_sales_report_daily,
            commands::reports::get_sales_report_weekly,
            commands::reports::get_sales_report_monthly,
            commands::reports::get_sales_report_yearly,
            commands::reports::get_sales_by_cashier,
            commands::reports::get_sales_by_payment_method,
            commands::reports::get_sales_discount_analysis,
            commands::reports::get_sales_returns_summary,
            commands::reports::get_sales_tax_summary,
            commands::reports::get_sales_quote_conversion,
            // Inventory Reports
            commands::reports::get_inventory_report,
            commands::reports::get_inventory_valuation,
            commands::reports::get_inventory_low_stock,
            commands::reports::get_inventory_movement_report,
            commands::reports::get_inventory_aging,
            commands::reports::get_inventory_overstock,
            commands::reports::get_inventory_fast_slow,
            // Purchasing Reports
            commands::reports::get_purchases_by_month,
            commands::reports::get_purchases_by_supplier,
            commands::reports::get_supplier_performance_report,
            commands::reports::get_po_status_summary,
            commands::reports::get_products_to_reorder,
            commands::reports::get_purchase_cost_history,
            // Customer Reports
            commands::reports::get_top_customers,
            commands::reports::get_customer_growth_report,
            commands::reports::get_customer_locations,
            commands::reports::get_inactive_customers,
            commands::reports::get_customer_credit_summary,
            commands::reports::get_customer_service_summary,
            // Supplier Reports
            commands::reports::get_supplier_ranking,
            commands::reports::get_lead_time_analysis,
            // Warehouse Reports
            commands::reports::get_warehouse_utilization,
            commands::reports::get_warehouse_stock_distribution,
            commands::reports::get_warehouse_adjustments,
            // Profitability
            commands::reports::get_profit_summary,
            commands::reports::get_profit_by_category,
            commands::reports::get_profit_by_product,
            commands::reports::get_profit_by_supplier,
            commands::reports::get_profit_by_brand,
            commands::reports::get_profit_by_customer,
            commands::reports::get_profit_by_warehouse,
            // KPIs
            commands::reports::get_kpi_values,
            commands::reports::get_kpi_definitions,
            // Saved / Scheduled / History
            commands::reports::get_saved_reports,
            commands::reports::create_saved_report,
            commands::reports::delete_saved_report,
            commands::reports::get_scheduled_reports,
            commands::reports::create_scheduled_report,
            commands::reports::toggle_scheduled_report,
            commands::reports::get_report_history,
            commands::reports::log_report_generation,
            commands::reports::get_report_templates,
            commands::reports::get_dashboard_preferences,
            commands::reports::save_dashboard_preferences,
            // ── Admin ──
            commands::admin::get_admin_dashboard,
            commands::admin::get_user_activity_chart,
            commands::admin::get_database_growth_chart,
            commands::admin::get_recent_audit_events,
            commands::admin::get_admin_users,
            commands::admin::get_admin_user,
            commands::admin::create_admin_user,
            commands::admin::update_admin_user,
            commands::admin::archive_admin_user,
            commands::admin::restore_admin_user,
            commands::admin::reset_user_password,
            commands::admin::lock_user_account,
            commands::admin::unlock_user_account,
            commands::admin::get_user_sessions,
            commands::admin::revoke_user_session,
            commands::admin::get_total_user_count,
            commands::admin::get_admin_roles,
            commands::admin::get_admin_role,
            commands::admin::get_all_permissions,
            commands::admin::get_permission_groups,
            commands::admin::create_admin_role,
            commands::admin::update_admin_role,
            commands::admin::clone_admin_role,
            commands::admin::archive_admin_role,
            commands::admin::assign_permissions_to_role,
            commands::admin::bulk_assign_permissions,
            commands::admin::get_app_settings,
            commands::admin::get_setting_categories,
            commands::admin::update_app_setting,
            commands::admin::update_app_settings_bulk,
            commands::admin::get_setting_history,
            commands::admin::reset_setting_to_default,
            commands::admin::get_backup_history,
            commands::admin::create_backup,
            commands::admin::delete_backup,
            commands::admin::get_restore_history,
            commands::admin::get_scheduled_backup_config,
            commands::admin::save_scheduled_backup_config,
            commands::admin::get_backup_stats,
            commands::admin::get_database_stats,
            commands::admin::get_table_sizes,
            commands::admin::vacuum_database,
            commands::admin::optimize_database,
            commands::admin::check_database_integrity,
            commands::admin::get_migration_status,
            commands::admin::reindex_database,
            commands::admin::get_printers,
            commands::admin::create_printer,
            commands::admin::update_printer,
            commands::admin::delete_printer,
            commands::admin::set_default_printer,
            commands::admin::test_printer,
            commands::admin::get_printer_types,
            commands::admin::get_devices,
            commands::admin::create_device,
            commands::admin::update_device,
            commands::admin::delete_device,
            commands::admin::test_device,
            commands::admin::get_device_types,
            commands::admin::get_system_updates,
            commands::admin::check_for_updates,
            commands::admin::get_current_version,
            commands::admin::record_update_available,
            commands::admin::mark_update_installed,
            commands::admin::run_diagnostics,
            commands::admin::get_diagnostic_history,
            commands::admin::save_diagnostic_report,
            commands::admin::get_diagnostic_summary,
            commands::admin::get_system_logs,
            commands::admin::get_support_package,
            commands::admin::get_audit_events,
            commands::admin::get_audit_event,
            commands::admin::get_audit_summary,
            commands::admin::get_audit_timeline,
            commands::admin::get_audit_by_action,
            commands::admin::get_audit_by_user,
            commands::admin::export_audit_logs,
            commands::admin::get_license_info,
            commands::admin::save_license,
            commands::admin::activate_license,
            commands::admin::deactivate_license,
            commands::admin::validate_license,
            commands::admin::get_maintenance_logs,
            commands::admin::run_maintenance,
            commands::admin::clear_audit_logs,
            commands::admin::get_storage_info,
            commands::admin::get_system_info,
        ])
        .run(tauri::generate_context!())
        .expect("Error while running tauri application");
}
