mod commands;
mod config;
mod db;
mod error;

use db::{init_database, DbState};
use std::sync::OnceLock;

static DB_STATE: OnceLock<DbState> = OnceLock::new();

pub fn run() {
    env_logger::init();

    let app_config = config::AppConfig::default();

    let db_path = app_config.db_path.to_string_lossy().to_string();

    if let Some(parent) = app_config.db_path.parent() {
        std::fs::create_dir_all(parent).expect("Failed to create database directory");
    }

    let conn = init_database(&db_path).expect("Failed to initialize database");

    let db_state = DbState::new(conn);
    DB_STATE.set(db_state).expect("Failed to set database state");

    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .invoke_handler(tauri::generate_handler![
            commands::app::get_app_version,
            commands::app::health_check,
            commands::app::greet,
            commands::app::run_seeds,
            commands::auth::login,
            commands::auth::logout,
            commands::auth::get_current_user,
            commands::auth::check_session,
            commands::auth::get_user_permissions_list,
            commands::auth::login_by_role,
            commands::settings::get_settings,
            commands::settings::get_setting,
            commands::settings::update_setting,
            commands::settings::get_settings_by_group,
            commands::inventory::get_categories,
            commands::inventory::create_category,
            commands::inventory::update_category,
            commands::inventory::archive_category,
            commands::inventory::restore_category,
            commands::inventory::get_brands,
            commands::inventory::create_brand,
            commands::inventory::update_brand,
            commands::inventory::archive_brand,
            commands::inventory::get_manufacturers,
            commands::inventory::create_manufacturer,
            commands::inventory::update_manufacturer,
            commands::inventory::get_suppliers,
            commands::inventory::create_supplier,
            commands::inventory::update_supplier,
            commands::inventory::archive_supplier,
            commands::inventory::get_warehouses,
            commands::inventory::create_warehouse,
            commands::inventory::update_warehouse,
            commands::inventory::get_storage_locations,
            commands::inventory::create_storage_location,
            commands::inventory::update_storage_location,
            commands::inventory::archive_storage_location,
            commands::inventory::get_products,
            commands::inventory::get_product,
            commands::inventory::create_product,
            commands::inventory::update_product,
            commands::inventory::archive_product,
            commands::inventory::restore_product,
            commands::inventory::get_dashboard_stats,
            commands::inventory::get_inventory_movements,
            commands::inventory::create_inventory_movement,
            commands::inventory::get_product_images,
            commands::inventory::create_product_image,
            commands::inventory::delete_product_image,
            commands::customers::get_customers,
            commands::customers::get_customer,
            commands::customers::create_customer,
            commands::customers::update_customer,
            commands::customers::archive_customer,
            commands::customers::get_customer_detail,
            commands::customers::get_customer_sales,
            commands::customers::get_credit_accounts,
            commands::customers::get_credit_account,
            commands::customers::create_credit_account,
            commands::customers::update_credit_account,
            commands::customers::get_credit_transactions,
            commands::customers::add_credit_transaction,
            commands::customers::get_communications,
            commands::customers::create_communication,
            commands::customers::get_customer_notes,
            commands::customers::create_customer_note,
            commands::customers::get_customer_timeline,
            commands::vehicles::get_vehicle_brands,
            commands::vehicles::create_vehicle_brand,
            commands::vehicles::update_vehicle_brand,
            commands::vehicles::get_vehicle_models,
            commands::vehicles::create_vehicle_model,
            commands::vehicles::get_vehicle_generations,
            commands::vehicles::create_vehicle_generation,
            commands::vehicles::get_vehicle_engines,
            commands::vehicles::create_vehicle_engine,
            commands::vehicles::get_vehicle_transmissions,
            commands::vehicles::create_vehicle_transmission,
            commands::vehicles::get_vehicle_fuels,
            commands::vehicles::create_vehicle_fuel,
            commands::vehicles::get_customer_vehicles,
            commands::vehicles::get_customer_vehicle,
            commands::vehicles::create_customer_vehicle,
            commands::vehicles::update_customer_vehicle,
            commands::vehicles::delete_customer_vehicle,
            commands::compatibility::get_product_compatibility,
            commands::compatibility::create_compatibility,
            commands::compatibility::delete_compatibility,
            commands::compatibility::search_compatible_products,
            commands::compatibility::get_recommendations_for_vehicle,
            commands::reminders::get_service_reminders,
            commands::reminders::get_service_reminder,
            commands::reminders::create_service_reminder,
            commands::reminders::update_service_reminder_status,
            commands::reminders::get_overdue_reminders,
            commands::warranty::get_warranties,
            commands::warranty::get_warranty,
            commands::warranty::create_warranty,
            commands::warranty::update_warranty_status,
            commands::warranty::get_expiring_warranties,
            commands::crm::get_crm_dashboard,
            commands::crm::get_customers_by_month,
            commands::sales::get_sales,
            commands::sales::get_sale,
            commands::sales::get_sale_items,
            commands::sales::create_sale,
            commands::sales::refund_sale,
            commands::sales::get_daily_closeout,
            commands::sales::search_products_for_pos,
            commands::sales::process_checkout,
            commands::sales::get_sale_payments,
            commands::sales::get_sales_summary,
            commands::sales::get_sales_chart_data,
            commands::sales::search_sales,
            commands::sales::get_quotes,
            commands::sales::get_quote,
            commands::sales::get_quote_items,
            commands::sales::create_quote,
            commands::sales::update_quote,
            commands::sales::delete_quote,
            commands::sales::update_quote_status,
            commands::sales::convert_quote_to_sale,
            commands::sales::get_cash_register_status,
            commands::sales::open_cash_register,
            commands::sales::close_cash_register,
            commands::sales::get_cash_register_sessions,
            commands::sales::close_daily_shift,
            commands::sales::get_daily_closings,
            commands::sales::get_receipts_for_sale,
            commands::sales::get_receipt,
            commands::sales::mark_receipt_printed,
            commands::purchases::get_purchase_orders,
            commands::purchases::get_purchase_order,
            commands::purchases::get_purchase_order_items,
            commands::purchases::create_purchase_order,
            commands::purchases::update_purchase_order,
            commands::purchases::update_purchase_order_status,
            commands::purchases::delete_purchase_order,
            commands::purchases::get_purchase_requests,
            commands::purchases::get_purchase_request,
            commands::purchases::get_purchase_request_items,
            commands::purchases::create_purchase_request,
            commands::purchases::update_purchase_request_status,
            commands::purchases::get_purchase_receipts,
            commands::purchases::get_purchase_receipt,
            commands::purchases::get_purchase_receipt_items,
            commands::purchases::receive_purchase_order,
            commands::purchases::get_purchase_returns,
            commands::purchases::get_purchase_return,
            commands::purchases::get_purchase_return_items,
            commands::purchases::create_purchase_return,
            commands::purchases::get_supplier_products,
            commands::purchases::create_supplier_product,
            commands::purchases::update_supplier_product,
            commands::purchases::delete_supplier_product,
            commands::purchases::get_cost_history,
            commands::purchases::get_purchase_dashboard,
            commands::purchases::get_reorder_suggestions,
            commands::purchases::get_supplier_performance,
        ])
        .run(tauri::generate_context!())
        .expect("Error while running tauri application");
}
